In [1]:
#Задание1
import numpy as np

In [2]:
np.arange(0, 10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [3]:
#Задание2
x = np.diag(np.arange(0, 10)[::-1], k=0)
print(sum(np.diagonal(x)))


45


In [4]:
#Задание3
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

In [5]:
a = np.array([[4, 2, 1], [0, 1, 3], [0, 5, 4]])
b = np.array([4, 12, -3])

In [6]:
from numpy import linalg

In [7]:
linalg.solve(a, b)

array([ 2.15909091, -5.18181818,  5.72727273])

In [8]:
np.allclose(np.dot(a, linalg.solve(a, b)), b)

True

In [9]:
#Задание4
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [10]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [11]:
class users_list_check:
    def __init__(self, format_='value'):
        self.format = 'value'
        
    def cosine(self, users_stats, next_user_stats):
        aLength = np.linalg.norm(users_stats)
        bLength = np.linalg.norm(next_user_stats)

        return np.dot(users_stats, next_user_stats)/(aLength * bLength)
    
    def user_ID(self):
        my_list = users_stats.tolist()
        value = self.cosine(users_stats, next_user_stats)
        my_new_list = value.tolist() #cosine(users_stats, next_user_stats).tolist()
        result = zip(my_list, my_new_list)
        i=0
        for el in result:
            i=i+1
            my_dict = {i:el}
            for keys,values in my_dict.items():
                if max(value) == values[1]:
                    print('Наибольшая схожесть с пользователем ID:', keys, 'значимость cos:', round(max(value),2))

In [12]:
users_list_check().cosine(users_stats, next_user_stats)

array([0.04688072, 0.23440362, 0.09376145, 0.23440362, 0.09376145,
       0.        , 0.        , 0.14064217, 0.        , 0.        ])

In [13]:
users_list_check().user_ID()

Наибольшая схожесть с пользователем ID: 2 значимость cos: 0.23
Наибольшая схожесть с пользователем ID: 4 значимость cos: 0.23
